### PR TITLE
Float parse fix

### LINKED ISSUE #331: Histogram computations parse some floats incorrectly
Example:
Load gapminder.json and look at the population histogram—lots of values are getting treated as two-digit numbers (likely that somewhere values are getting converted to 13e7, and then `parseFloat` is only pulling out the 13).

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Fixes #331 

Turns out the bins and counts were actually accurate; the human-readable labels were incorrectly formatted. This PR fixes these format issues, and polishes them a little (using D3.format to get nicer number labels, and fixing a couple date label oddities).

### CODE REVIEW

File: app/resonant-laboratory/models/Dataset.js [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import d3 from 'd3';
```
Comment (ronichoudhury) [inline app/resonant-laboratory/models/Dataset.js]: Small style concern - the "modern" d3 way to do this is something like `import format from 'd3-format';` and then use `format()` directly in the code. What do you think?

Comment (alex-r-bigelow) [inline app/resonant-laboratory/models/Dataset.js]: Yeah, that's D3 v4... It will take a lot of revision across the app, so we tucked it all in #280. For now, I'm sticking with D3 v3.

Comment (ronichoudhury) [inline app/resonant-laboratory/models/Dataset.js]: Sounds good!

**Comment by ronichoudhury** [comment]
LGTM.
